name: My First Github Action
on: [push]
jobs:
        print-hello-world:
                runs-on: ubuntu-latest
                steps:
                        - run: echo "Hello World !!!!"
                        - run: echo "this is step no 2"
        print-hello-world2:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - uses: actions/setup-node@v3
                          with:
                                  node-version: "14.7.0"
                        - run: npm install
                          name: Install packages
                        - name: Build App
                          run: npm run build
